### ISSUE TITLE
求个友链～

### ISSUE THREAD

**Issue by richardchien** [ryan4yin/ryan4yin.space#10]
站点名称：Project RC
站点地址：https://stdrc.cc/
个人形象：https://avatars.githubusercontent.com/u/5317095?s=96&v=4
站点描述：一只腊鸡的技术成长。

**Comment by ryan4yin** [comment]
@richardchien 哇哦，是 RC，已加~

**Comment by richardchien** [comment]
我有罪，github 那个 avatar 链接似乎不能在你的站上显示，麻烦换一下这个 https://www.gravatar.com/avatar/be48464eb8308c31c693778a16813ee6?s=240 哈哈哈
