### ISSUE TITLE
申请与贵站成为友链

### ISSUE THREAD

**Issue by hsiaofongw** [ryan4yin/ryan4yin.space#3]
虽然素未谋面，但是因为觉得贵站的文章都写得很不错，斗胆向阁下提出申请，希望能互相成为友链：

站点名称：探索子
站点地址：https://exploro.one
站点头像：https://www.gravatar.com/avatar/dfa26ed25a72c40d602d33d854dd6f07?s=240
站点描述：Learn by doing.

**Comment by ryan4yin** [comment]
已添加，探索子的博客我也有读过，久仰大名了哈哈~

**Comment by hsiaofongw** [comment]
哇这么快就通过了hh
